import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { AddressInfo } from "node:net";
import { strToU8, zipSync } from "fflate";
import {
  slicerSidecarAdapter,
  slicerSidecarSlice,
  SlicerSidecarError,
} from "./slicer-sidecar.js";

type Handler = (req: IncomingMessage, res: ServerResponse, body: Buffer) => void;

let server: Server;
let baseUrl: string;
let handler: Handler;
/** Requests the fake sidecar saw, for asserting what PP actually sent. */
let seen: Array<{ url: string; body: string }> = [];

function json(res: ServerResponse, status: number, payload: unknown): void {
  const text = JSON.stringify(payload);
  res.writeHead(status, { "content-type": "application/json" });
  res.end(text);
}

beforeAll(async () => {
  server = createServer((req, res) => {
    const chunks: Buffer[] = [];
    req.on("data", (c: Buffer) => chunks.push(c));
    req.on("end", () => {
      const body = Buffer.concat(chunks);
      seen.push({ url: req.url ?? "", body: body.toString("latin1") });
      handler(req, res, body);
    });
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const { port } = server.address() as AddressInfo;
  baseUrl = `http://127.0.0.1:${port}`;
});

afterAll(async () => {
  await new Promise<void>((resolve) => server.close(() => resolve()));
});

function reset(): void {
  seen = [];
}

const GCODE = "; generated by fake slicer\nG28\nG1 X10 Y10 F3000\n";
// 1x1 transparent PNG.
const PNG_B64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";

function forgeFirstEntryExpandedSize(zip: Uint8Array, expandedSize: number): Buffer {
  const forged = Buffer.from(zip);
  const localHeader = forged.indexOf(Buffer.from([0x50, 0x4b, 0x03, 0x04]));
  const centralHeader = forged.indexOf(Buffer.from([0x50, 0x4b, 0x01, 0x02]));
  if (localHeader < 0 || centralHeader < 0) throw new Error("ZIP fixture has no file entry");
  forged.writeUInt32LE(expandedSize, localHeader + 22);
  forged.writeUInt32LE(expandedSize, centralHeader + 24);
  return forged;
}

describe("slicerSidecarSlice — v1 protocol", () => {
  it("posts file/slicer/resolved_flat_configs and decodes the base64 reply", async () => {
    reset();
    handler = (req, res) => {
      expect(req.url).toBe("/v1/slice");
      json(res, 200, {
        ok: true,
        meta: { slicer: "prusa", stub: false, duration_ms: 12, warnings: ["fyi"] },
        gcode_filename: "plate_1.gcode",
        gcode_base64: Buffer.from(GCODE).toString("base64"),
        thumbnail_filename: "plate_1.png",
        thumbnail_base64: PNG_B64,
      });
    };

    const result = await slicerSidecarSlice(
      { url: baseUrl, slicer: "prusa" },
      {
        model: new Uint8Array([0x50, 0x4b, 0x03, 0x04]),
        filename: "kit_prusa_xl_plate_01.3mf",
        slicer: "prusa",
        resolved_flat_configs: {
          machine: { printer_model: "XL" },
          process: { layer_height: "0.2" },
          filament: { filament_type: "PLA" },
        },
        timeout_s: 42,
      },
    );

    expect(Buffer.from(result.gcode).toString()).toBe(GCODE);
    // A real PNG signature, not just non-empty bytes.
    expect(Buffer.from(result.thumbnail.slice(0, 8))).toEqual(
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    );
    expect(result.filename).toBe("plate_1.gcode");
    expect(result.thumbnail_filename).toBe("plate_1.png");
    expect(result.protocol).toBe("v1");
    expect(result.warnings).toEqual(["fyi"]);

    const sent = seen[0]!;
    expect(sent.url).toBe("/v1/slice");
    expect(sent.body).toContain('name="slicer"');
    expect(sent.body).toContain("prusa");
    expect(sent.body).toContain('name="resolved_flat_configs"');
    expect(sent.body).toContain('"printer_model":"XL"');
    expect(sent.body).toContain('name="timeout_s"');
    expect(sent.body).toContain("42");
    expect(sent.body).toContain("kit_prusa_xl_plate_01.3mf");
  });

  it("surfaces the sidecar's structured error envelope", async () => {
    reset();
    handler = (_req, res) => {
      json(res, 502, {
        ok: false,
        error: {
          code: "slicer_execution_failed",
          message: "orca-slicer exited with code 1.",
          details: { exit_code: 1, stderr: "bad 3mf" },
        },
      });
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca" },
        { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
      ),
    ).rejects.toMatchObject({
      code: "slicer_execution_failed",
      status: 502,
      message: "orca-slicer exited with code 1.",
    });
  });

  it("rejects an oversized sidecar error response from its headers", async () => {
    reset();
    handler = (_req, res) => {
      res.writeHead(502, {
        "content-type": "text/plain",
        "content-length": String(64 * 1024 + 1),
      });
      res.end("short");
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca" },
        { model: new Uint8Array([1]), slicer: "orca" },
      ),
    ).rejects.toMatchObject({ code: "response_too_large", status: 502 });
  });

  it("rejects an empty-gcode 200 rather than writing a zero-byte file", async () => {
    reset();
    handler = (_req, res) => {
      json(res, 200, {
        ok: true,
        meta: { slicer: "orca", duration_ms: 1, warnings: [] },
        gcode_filename: "plate_1.gcode",
        gcode_base64: "",
        thumbnail_filename: "plate_1.png",
        thumbnail_base64: PNG_B64,
      });
    };

    const err = await slicerSidecarSlice(
      { url: baseUrl, slicer: "orca" },
      { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
    ).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(SlicerSidecarError);
    expect((err as SlicerSidecarError).code).toBe("empty_gcode");
  });

  it("rejects a malformed successful payload at the sidecar boundary", async () => {
    reset();
    handler = (_req, res) => {
      json(res, 200, {
        ok: true,
        gcode_base64: 42,
      });
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca", api: "v1" },
        { model: new Uint8Array([1]), slicer: "orca" },
      ),
    ).rejects.toMatchObject({ code: "invalid_response" });
  });
});

describe("slicerSidecarSlice — legacy fallback", () => {
  it("retries /slice when /v1/slice is not implemented", async () => {
    reset();
    handler = (req, res) => {
      if (req.url === "/v1/slice") {
        res.writeHead(404, { "content-type": "text/plain" });
        res.end("Not Found");
        return;
      }
      json(res, 200, {
        gcode: Buffer.from(GCODE).toString("base64"),
        thumbnail: PNG_B64,
        filename: "plate_1.gcode",
      });
    };

    const result = await slicerSidecarSlice(
      { url: baseUrl, slicer: "orca" },
      {
        model: new Uint8Array([1]),
        slicer: "orca",
        resolved_flat_configs: {
          machine: { printer_model: "Voron350" },
          process: { layer_height: "0.2" },
          filament: { filament_type: "PLA" },
          filament_2: { filament_type: "PETG" },
        },
      },
    );

    expect(result.protocol).toBe("legacy");
    expect(Buffer.from(result.gcode).toString()).toBe(GCODE);
    expect(seen.map((s) => s.url)).toEqual(["/v1/slice", "/slice"]);

    // resolved_flat_configs must be split onto the legacy field names, with
    // every filament* key collected into the filament_configs array.
    const legacy = seen[1]!.body;
    expect(legacy).toContain('name="machine_config"');
    expect(legacy).toContain('name="process_config"');
    expect(legacy).toContain('name="filament_configs"');
    expect(legacy).toContain('"filament_type":"PLA"');
    expect(legacy).toContain('"filament_type":"PETG"');
  });

  it("does NOT fall back when the sidecar reports a real slicing failure", async () => {
    reset();
    handler = (_req, res) => {
      json(res, 502, {
        ok: false,
        error: { code: "slicer_timeout", message: "timed out", details: {} },
      });
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca" },
        { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
      ),
    ).rejects.toMatchObject({ code: "slicer_timeout" });
    // A 502 is the slicer failing, not a missing endpoint — retrying legacy
    // would slice twice and hide the real error.
    expect(seen.map((s) => s.url)).toEqual(["/v1/slice"]);
  });

  it("honours an explicit api=legacy pin without probing v1", async () => {
    reset();
    handler = (_req, res) => {
      json(res, 200, { gcode: Buffer.from(GCODE).toString("base64"), thumbnail: "" });
    };
    const result = await slicerSidecarSlice(
      { url: baseUrl, slicer: "orca", api: "legacy" },
      { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
    );
    expect(result.protocol).toBe("legacy");
    expect(seen.map((s) => s.url)).toEqual(["/slice"]);
  });

  it("rejects a legacy JSON payload with no G-code", async () => {
    reset();
    handler = (_req, res) => {
      json(res, 200, { thumbnail: PNG_B64 });
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca", api: "legacy" },
        { model: new Uint8Array([1]), slicer: "orca" },
      ),
    ).rejects.toMatchObject({ code: "empty_gcode" });
  });

  it("rejects an empty legacy raw response", async () => {
    reset();
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "text/plain" });
      res.end();
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca", api: "legacy" },
        { model: new Uint8Array([1]), slicer: "orca" },
      ),
    ).rejects.toMatchObject({ code: "empty_gcode" });
  });

  it("does not re-POST /slice after a transient socket drop (no second CLI job)", async () => {
    reset();
    let posts = 0;
    handler = (req, res) => {
      if (req.method === "POST" && req.url === "/slice") {
        posts += 1;
        // Drop the socket without an HTTP response → undici TypeError / fetch failed.
        req.socket.destroy();
        return;
      }
      res.writeHead(404).end();
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca", api: "legacy" },
        { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
      ),
    ).rejects.toBeTruthy();

    expect(posts).toBe(1);
    expect(seen.filter((s) => s.url === "/slice")).toHaveLength(1);
  });

  it("retries a dropped GET health probe once (idempotent)", async () => {
    reset();
    let healthHits = 0;
    handler = (req, res) => {
      if (req.url === "/health") {
        healthHits += 1;
        if (healthHits === 1) {
          req.socket.destroy();
          return;
        }
        return json(res, 200, { status: "ok" });
      }
      res.writeHead(404).end();
    };
    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl, slicer: "orca" });
    expect(result.ok).toBe(true);
    expect(healthHits).toBeGreaterThanOrEqual(2);
  });

  it("rejects when no url is configured", async () => {
    await expect(
      slicerSidecarSlice({}, { model: new Uint8Array([1]), slicer: "orca" }),
    ).rejects.toMatchObject({ code: "no_url" });
  });

  it("extracts gcode and thumbnail from a legacy zip body", async () => {
    reset();
    const zip = zipSync({
      "plate_1.gcode": strToU8(GCODE),
      "Metadata/plate_1.png": Uint8Array.from(Buffer.from(PNG_B64, "base64")),
    });
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "application/zip" });
      res.end(Buffer.from(zip));
    };

    const result = await slicerSidecarSlice(
      { url: baseUrl, slicer: "orca", api: "legacy" },
      { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
    );

    expect(result.protocol).toBe("legacy");
    expect(Buffer.from(result.gcode).toString()).toBe(GCODE);
    expect(Buffer.from(result.thumbnail.slice(0, 8))).toEqual(
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    );
    expect(result.thumbnail_filename).toBe("plate_1.png");
  });

  it("rejects a zip content-type whose body is not a zip", async () => {
    reset();
    const garbage = Buffer.from("this is not a zip archive");
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "application/zip" });
      res.end(garbage);
    };

    const err = await slicerSidecarSlice(
      { url: baseUrl, slicer: "orca", api: "legacy" },
      { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
    ).catch((e: unknown) => e);

    expect(err).toBeInstanceOf(SlicerSidecarError);
    expect((err as SlicerSidecarError).code).toBe("invalid_zip");
  });

  it("rejects a zip that contains no gcode", async () => {
    reset();
    const zip = zipSync({ "readme.txt": strToU8("no gcode here") });
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "application/zip" });
      res.end(Buffer.from(zip));
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca", api: "legacy" },
        { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
      ),
    ).rejects.toMatchObject({ code: "empty_gcode" });
  });

  it("rejects a zip whose declared expanded size exceeds the sidecar budget", async () => {
    reset();
    const zip = Buffer.from(zipSync({ "plate_1.gcode": strToU8("G28\n") }));
    const centralDirectory = zip.indexOf(Buffer.from([0x50, 0x4b, 0x01, 0x02]));
    expect(centralDirectory).toBeGreaterThanOrEqual(0);
    zip.writeUInt32LE(0xffff_ffff, centralDirectory + 24);
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "application/zip" });
      res.end(zip);
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca", api: "legacy" },
        { model: new Uint8Array([1]), slicer: "orca" },
      ),
    ).rejects.toMatchObject({ code: "archive_too_large" });
  });

  it("rejects a zip whose entry understates its actual expanded bytes", async () => {
    reset();
    const payload = Uint8Array.from(
      { length: 8 * 1024 },
      (_unused, index) => (index * 31 + Math.floor(index / 7)) & 0xff,
    );
    const zip = forgeFirstEntryExpandedSize(
      zipSync({ "plate_1.gcode": payload }, { level: 6 }),
      1,
    );
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "application/zip" });
      res.end(zip);
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca", api: "legacy" },
        { model: new Uint8Array([1]), slicer: "orca" },
      ),
    ).rejects.toMatchObject({ code: "invalid_zip" });
  });

  it("rejects a high-ratio zip from actual emitted bytes", async () => {
    reset();
    const payload = strToU8("G1 X0 Y0 E0\n".repeat(100_000));
    const zip = zipSync({ "plate_1.gcode": payload }, { level: 9 });
    expect(payload.byteLength).toBeGreaterThan(zip.byteLength * 200);
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "application/zip" });
      res.end(Buffer.from(zip));
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca", api: "legacy" },
        { model: new Uint8Array([1]), slicer: "orca" },
      ),
    ).rejects.toMatchObject({ code: "archive_too_large" });
  });

  it("does not inflate irrelevant high-ratio entries", async () => {
    reset();
    const zip = zipSync(
      {
        "debug/repeated.txt": new Uint8Array(2 * 1024 * 1024),
        "plate_1.gcode": strToU8(GCODE),
      },
      { level: 9 },
    );
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "application/zip" });
      res.end(Buffer.from(zip));
    };

    const result = await slicerSidecarSlice(
      { url: baseUrl, slicer: "orca", api: "legacy" },
      { model: new Uint8Array([1]), slicer: "orca" },
    );

    expect(Buffer.from(result.gcode).toString()).toBe(GCODE);
  });

  it("counts irrelevant entries toward the archive entry cap", async () => {
    reset();
    const entries: Record<string, Uint8Array> = { "plate_1.gcode": strToU8(GCODE) };
    for (let index = 0; index < 256; index += 1) {
      entries[`debug/${index}.txt`] = new Uint8Array(0);
    }
    const zip = zipSync(entries);
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "application/zip" });
      res.end(Buffer.from(zip));
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca", api: "legacy" },
        { model: new Uint8Array([1]), slicer: "orca" },
      ),
    ).rejects.toMatchObject({ code: "archive_too_large" });
  });
});

describe("slicerSidecarAdapter.testConnection", () => {
  it("passes against a v1 sidecar (/healthz)", async () => {
    reset();
    handler = (req, res) => {
      if (req.url === "/healthz") return json(res, 200, { ok: true });
      res.writeHead(404).end();
    };
    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl, slicer: "prusa" });
    expect(result.ok).toBe(true);
    expect(result.message).toContain("prusa");
    expect(result.message).toContain("v1");
  });

  it("passes against a legacy sidecar (/health only)", async () => {
    reset();
    handler = (req, res) => {
      if (req.url === "/health") return json(res, 200, { status: "ok" });
      res.writeHead(404).end();
    };
    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl, slicer: "orca" });
    expect(result.ok).toBe(true);
    expect(result.message).toContain("legacy");
  });

  it("fails when legacy health reports a missing slicer binary", async () => {
    reset();
    handler = (req, res) => {
      if (req.url === "/health") {
        return json(res, 200, {
          status: "ok",
          slicer: "orca",
          bin: "/missing/orca-slicer",
          exists: false,
        });
      }
      res.writeHead(404).end();
    };

    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl, slicer: "orca" });
    expect(result.ok).toBe(false);
  });

  it("fails when a health endpoint explicitly reports an unhealthy status", async () => {
    reset();
    handler = (req, res) => {
      if (req.url === "/healthz") return json(res, 200, { ok: false });
      if (req.url === "/health") return json(res, 200, { status: "unhealthy" });
      res.writeHead(404).end();
    };

    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl, slicer: "orca" });
    expect(result.ok).toBe(false);
  });

  it("fails when a JSON health response is malformed", async () => {
    reset();
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "application/json" });
      res.end("{not-json");
    };

    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl, slicer: "orca" });
    expect(result.ok).toBe(false);
  });

  it("fails when a JSON health response has no positive health signal", async () => {
    reset();
    handler = (_req, res) => json(res, 200, {});

    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl, slicer: "orca" });
    expect(result.ok).toBe(false);
  });

  it("accepts a successful plain-text health response for legacy compatibility", async () => {
    reset();
    handler = (_req, res) => {
      res.writeHead(200, { "content-type": "text/plain" });
      res.end("ok");
    };

    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl, slicer: "orca" });
    expect(result.ok).toBe(true);
  });

  it("cancels health bodies that it does not parse", async () => {
    const nonOkCancel = vi.fn();
    const plainTextCancel = vi.fn();
    const responseWithOpenBody = (
      status: number,
      contentType: string,
      cancel: () => void,
    ) => new Response(
      new ReadableStream({
        start(controller) {
          controller.enqueue(new TextEncoder().encode("unused"));
        },
        cancel,
      }),
      { status, headers: { "content-type": contentType } },
    );
    vi.stubGlobal("fetch", vi.fn(async (input: string | URL | Request) =>
      String(input).endsWith("/healthz")
        ? responseWithOpenBody(503, "text/plain", nonOkCancel)
        : responseWithOpenBody(200, "text/plain", plainTextCancel),
    ));

    try {
      await expect(
        slicerSidecarAdapter.testConnection({ url: "http://127.0.0.1:2814" }),
      ).resolves.toMatchObject({ ok: true });
      expect(nonOkCancel).toHaveBeenCalledOnce();
      expect(plainTextCancel).toHaveBeenCalledOnce();
    } finally {
      vi.unstubAllGlobals();
    }
  });

  it("fails when neither health endpoint answers", async () => {
    reset();
    handler = (_req, res) => {
      res.writeHead(500).end();
    };
    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl });
    expect(result.ok).toBe(false);
  });

  it("fails cleanly with no url", async () => {
    const result = await slicerSidecarAdapter.testConnection({});
    expect(result.ok).toBe(false);
    expect(result.message).toContain("url is required");
  });
});
