[package]
name = "pp-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
pp-core = { path = "../pp-core" }
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "=2.12.1", features = ["tray-icon"] }
rfd = { version = "=0.17.2", default-features = false, features = ["gtk3"] }

[build-dependencies]
tauri-build = "=2.7.1"
