[package]
name = "pp-source"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
fs2.workspace = true
rustix = { version = "=1.1.5", features = ["fs"] }
unicode-normalization = "=0.1.24"
caseless = "=0.2.2"
zip = { version = "=8.6.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }
regex = "=1.13.1"
ryu-js = "=1.0.2"
icu_collator = "=2.3.1"
getrandom = "=0.3.4"
