[package]
name = "pp-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
fs2.workspace = true
rand.workspace = true
sha2.workspace = true
hex.workspace = true
time = { version = "=0.3.55", features = ["std", "parsing"] }
argon2 = { version = "=0.5.3", default-features = false, features = ["alloc", "password-hash"] }
scrypt = { version = "=0.11.0", default-features = false }
base64 = "=0.22.1"
subtle = { version = "=2.6.1", default-features = false }
hmac.workspace = true
getrandom = "=0.3.4"
icu_collator = "=2.3.1"
regress = "=0.11.1"
ryu-js = "=1.0.2"

pp-contracts = { path = "../pp-contracts" }
saphyr-parser = { version = "=0.1.0", default-features = false }
