import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,copyFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {SqliteDatabase,getDb} from '../../apps/server/src/db/client.ts';
import {digestPlanDraft} from '../../apps/server/src/services/plan-drafts.ts';
import {AppRepository} from '../../apps/server/src/db/repository.ts';
const output=process.argv[2];mkdirSync(output,{recursive:true});
function dump(raw){return Object.fromEntries(raw.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all().map(({name})=>{const columns=raw.prepare(`PRAGMA table_info("${name}")`).all();const keys=columns.filter(c=>c.pk).sort((a,b)=>a.pk-b.pk);return[name,raw.prepare(`SELECT * FROM "${name}" ORDER BY ${(keys.length?keys:columns).map(c=>`"${c.name}"`).join(',')}`).all()]}))}
for(const name of ['first','unchanged','growth','shrink','excluded','prior-completion','replace','missing-selection','unresolved','stale-progress','stale-digest','stale-lifecycle','stale-base','archived','foreign','moved-attachment','pinned-source','collision','collision-exhausted','production-active','remap-unchanged','shrink-watch-surplus','shrink-watch-survivor','rollback','legacy-baseline','live-filament','unexclude','empty-link','queue-active','foreign-collision']){
 const root=output+'/'+name;mkdirSync(root,{recursive:true});const database=new SqliteDatabase(root);database.connect();const raw=database.sqlite;let counter=0;let consumed=[];let supplied=null;
 const repo=new AppRepository(getDb(database),'default',database.reposDir,undefined,{tokenFactory:()=>{const token=supplied?supplied.shift():`ppu_${(++counter).toString(16).padStart(32,'0')}`;consumed.push(token);return token}});
 const source=repo.createSource({name:'Publication Source',url:'https://example.test/local',source_kind:'github'});const observed=repo.getProjectRow(source.id);const locator=`${source.id}/revisions/fixture`;mkdirSync(database.reposDir+'/'+locator,{recursive:true});writeFileSync(database.reposDir+'/'+locator+'/bracket.stl','solid bracket\nendsolid bracket\n');
 const revision=repo.recordSourceRevision({sourceId:source.id,upstreamRevisionKey:'fixture',manifestDigest:'a'.repeat(64),snapshotLocator:locator,syncedAt:new Date().toISOString(),completeness:'complete'});repo.activateSourceRevision({sourceId:source.id,revisionId:revision.id,observed,sourceVersion:'fixture'});const profile=repo.createProfile('Publication Build',source.id);
 raw.prepare("INSERT INTO users(id,email,display_name,password_hash,is_admin,created_at) VALUES('default','publication@example.test','Fixture',NULL,1,?)").run(new Date().toISOString());raw.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,'default','2099-01-01T00:00:00.000Z')").run(createHash('sha256').update('publication-fixture-secret').digest('hex'));
 const foreign=new AppRepository(getDb(database),'foreign',database.reposDir);foreign.createProfile('Foreign Build');foreign.setSetting('protected','unchanged');
 function draft(key){const result=repo.recomputePlanDraft({profileId:profile.id,actor:'default',idempotencyKey:key,preferAccepted:true});assert.equal(result.kind,'created');return result.draft}
 function select(d,key,decisions=[]){const result=repo.savePlanDraftRequiredUnitReconciliation({profileId:profile.id,draftId:d.id,expectedSnapshotDigest:d.snapshotDigest,decisions,actorId:'default',idempotencyKey:key});assert.equal(result.kind,'saved');return result.draft}
 function command(d,key){return{profileId:profile.id,draftId:d.id,expectedSnapshotDigest:d.snapshotDigest,expectedLifecycleVersion:d.lifecycleVersion,expectedBase:d.baseRevisionId===null?{kind:'empty',planVersion:0}:{kind:'revision',revisionId:d.baseRevisionId,planVersion:d.basePlanVersion},actorId:'default',idempotencyKey:key,remapCheckoffLinks:true}}
 let d=draft('initial');
 if(!['first','legacy-baseline'].includes(name)){
  const edit=repo.editPlanDraftParts({profileId:profile.id,draftId:d.id,expectedSnapshotDigest:d.snapshotDigest,decision:{kind:'set_quantity_override',partIds:[d.parts[0].id],value:3}});d=edit.draft;if(name==='unexclude'){d=repo.editPlanDraftParts({profileId:profile.id,draftId:d.id,expectedSnapshotDigest:d.snapshotDigest,decision:{kind:'set_included',partIds:[d.parts[0].id],value:false}}).draft;}d=select(d,'baseline');assert.equal(repo.applyPlanChanges(command(d,'baseline')).kind,'applied');
  const old=repo.readAcceptedPlanOperationalSnapshot(profile.id);assert.equal(old.kind,'ready');const a=old.snapshot;const plates=name==='unexclude'?null:repo.publishAcceptedPlates({profileId:profile.id,expected:{profileId:profile.id,revisionId:a.revisionId,planVersion:a.planVersion,revisionDigest:a.revisionDigest,requiredUnitMappingDigest:a.requiredUnitMappingDigest},expectedPlateRevisionId:null,plates:[{plateId:'fixture-plate',printerId:'fixture-printer',printerName:'Fixture Printer',printerModel:'Fixture Model',bedWidthUm:600000,bedDepthUm:500000,bedHeightUm:220000,marginUm:5000,units:a.parts.filter(p=>p.included).flatMap(p=>p.units).map((u,index)=>({token:u.token,xUm:5000+60000*index,yUm:5000,widthUm:50000,depthUm:40000,heightUm:30000}))}]});if(plates)assert.equal(plates.kind,'published');const part=old.snapshot.parts[0];raw.prepare('UPDATE print_progress SET completed=1 WHERE tenant_id=? AND part_id=? AND unit_index=2').run('default',part.projectionPartId);
  if(['production-active','remap-unchanged','shrink-watch-surplus','shrink-watch-survivor'].includes(name))repo.setSetting('printer.checkoff_links',JSON.stringify([{id:'watch',filename:'bracket.stl',profile_id:profile.id,state:'watching',units:[{part_id:part.projectionPartId,unit_index:name==='shrink-watch-surplus'?0:2}],resolved_units:[]}]));
  d=draft('working');const edited=repo.editPlanDraftParts({profileId:profile.id,draftId:d.id,expectedSnapshotDigest:d.snapshotDigest,decision:{kind:'set_quantity_override',partIds:[d.parts[0].id],value:['growth','collision','collision-exhausted','foreign-collision'].includes(name)?5:['shrink','stale-progress','shrink-watch-surplus','shrink-watch-survivor'].includes(name)?1:3}});d=edited.draft;
 }
 let decisions=[];
 if(['excluded','unexclude'].includes(name)){const edit=repo.editPlanDraftParts({profileId:profile.id,draftId:d.id,expectedSnapshotDigest:d.snapshotDigest,decision:{kind:'set_included',partIds:[d.parts[0].id],value:name==='unexclude'}});d=edit.draft;}
 if(['prior-completion','replace','unresolved'].includes(name)){d.parts[0].artifactDigest='b'.repeat(64);raw.prepare('UPDATE plan_draft_parts SET artifact_digest=? WHERE id=?').run('b'.repeat(64),d.parts[0].id);d.snapshotDigest=digestPlanDraft(d);raw.prepare('UPDATE plan_drafts SET snapshot_digest=? WHERE id=?').run(d.snapshotDigest,d.id);if(name==='prior-completion')decisions=[{kind:'accept_prior_completion',targetDraftPartId:d.parts[0].id,predecessorRevisionPartId:d.parts[0].baseRevisionPartId}];if(name==='replace')decisions=[{kind:'replace',targetDraftPartId:d.parts[0].id}];}
 if(name!=='missing-selection')d=select(d,'selected',decisions);
 const c=command(d,'publish');const request={expected_snapshot_digest:d.snapshotDigest,expected_lifecycle_version:d.lifecycleVersion,expected_base:{revision_id:d.baseRevisionId,plan_version:d.basePlanVersion},remap_checkoff_links:true};
 if(name==='stale-progress')raw.prepare('UPDATE print_progress SET completed=0,assembled=0').run();
 if(name==='stale-digest'){request.expected_snapshot_digest='f'.repeat(64);c.expectedSnapshotDigest=request.expected_snapshot_digest;}
 if(name==='stale-lifecycle'){request.expected_lifecycle_version=1;c.expectedLifecycleVersion=1;}
 if(name==='stale-base'){request.expected_base.plan_version+=1;c.expectedBase.planVersion+=1;}
 if(name==='archived')raw.prepare('UPDATE build_profiles SET archived_at=? WHERE id=?').run(new Date().toISOString(),profile.id);
 if(name==='foreign'){c.profileId=2;}
 if(name==='moved-attachment')raw.prepare('UPDATE profile_layers SET layer_order=1 WHERE profile_id=?').run(profile.id);
 if(name==='pinned-source'){const moved=repo.recordSourceRevision({sourceId:source.id,upstreamRevisionKey:'moved',manifestDigest:'b'.repeat(64),snapshotLocator:locator,syncedAt:new Date().toISOString(),completeness:'complete'});repo.activateSourceRevision({sourceId:source.id,revisionId:moved.id,observed:repo.getProjectRow(source.id),sourceVersion:'moved'});repo.setSetting('naming.stl_profile','{}');}
 if(name==='empty-link')repo.setSetting('printer.checkoff_links',JSON.stringify([{id:'empty',profile_id:profile.id,state:'awaiting_verify',units:[]}]));
 if(name==='queue-active')repo.setSetting('printer.send_queue',JSON.stringify([{id:'queue',filename:'bracket.stl',profile_id:profile.id,state:'error',checkoff_units:[{part_id:1,unit_index:0}]}]));
 if(['production-active','empty-link','queue-active'].includes(name)){request.remap_checkoff_links=false;c.remapCheckoffLinks=false;}
 if(name==='rollback')raw.exec("CREATE TRIGGER publication_fixture_abort BEFORE INSERT ON plan_apply_requests BEGIN SELECT RAISE(ABORT,'fixture publication constraint'); END");
 if(name==='legacy-baseline')raw.prepare("INSERT INTO parts(tenant_id,profile_id,match_key,relative_path,filename,source_layer,status,role,quantity_auto,quantity_effective,included,notes) VALUES('default',?,'legacy','legacy.stl','legacy.stl','base:Publication Source','new','primary',1,1,1,'')").run(profile.id);
 if(name==='live-filament')raw.prepare("UPDATE parts SET filament_custom_hex='#112233' WHERE profile_id=?").run(profile.id);
 let transcript=Array.from({length:8},(_,i)=>`ppu_${(counter+i+1).toString(16).padStart(32,'0')}`);consumed=[];
 if(name==='foreign-collision'){
  const source=foreign.createSource({name:'Foreign Source',url:'https://example.test/foreign',source_kind:'github'});const locator=`${source.id}/revisions/fixture`;mkdirSync(database.reposDir+'/'+locator,{recursive:true});writeFileSync(database.reposDir+'/'+locator+'/foreign.stl','solid foreign\nendsolid foreign\n');const observed=foreign.getProjectRow(source.id);const revision=foreign.recordSourceRevision({sourceId:source.id,upstreamRevisionKey:'fixture',manifestDigest:'c'.repeat(64),snapshotLocator:locator,syncedAt:new Date().toISOString(),completeness:'complete'});foreign.activateSourceRevision({sourceId:source.id,revisionId:revision.id,observed,sourceVersion:'fixture'});const build=foreign.createProfile('Foreign accepted',source.id);let working=foreign.recomputePlanDraft({profileId:build.id,actor:'foreign',idempotencyKey:'foreign'});assert.equal(working.kind,'created');let selected=foreign.savePlanDraftRequiredUnitReconciliation({profileId:build.id,draftId:working.draft.id,expectedSnapshotDigest:working.draft.snapshotDigest,decisions:[],actorId:'foreign',idempotencyKey:'foreign'});assert.equal(selected.kind,'saved');let published=foreign.applyPlanChanges({profileId:build.id,draftId:working.draft.id,expectedSnapshotDigest:selected.draft.snapshotDigest,expectedLifecycleVersion:0,expectedBase:{kind:'empty',planVersion:0},actorId:'foreign',idempotencyKey:'foreign'});assert.equal(published.kind,'applied');const token=raw.prepare('SELECT token FROM required_units WHERE tenant_id=?').get('foreign').token;transcript=[token,...transcript];
 }
 if(name==='collision')transcript=['ppu_'+(1).toString(16).padStart(32,'0'),...transcript];
 if(name==='collision-exhausted')transcript=Array(32).fill('ppu_'+(1).toString(16).padStart(32,'0'));
 supplied=[...transcript];
 raw.pragma('wal_checkpoint(TRUNCATE)');copyFileSync(root+'/print-partner.db',root+'/before.db');const before=dump(raw);const started=new Date().toISOString();let result;let replay;try{result=repo.applyPlanChanges(c);if(!['applied','existing','already_applied'].includes(result.kind))supplied=[...transcript];replay=repo.applyPlanChanges(['applied','existing','already_applied'].includes(result.kind)?{...c,remapCheckoffLinks:!c.remapCheckoffLinks}:c);}catch(error){assert.equal(name,'rollback');result={error:error.message};replay=null;}const ended=new Date().toISOString();const after=dump(raw);
 writeFileSync(root+'/case.json',JSON.stringify({name,profile:c.profileId,draft:d.id,key:'publish',request,transcript,consumed,started,ended,result,replay,before,after}));writeFileSync(root+'/request.json',JSON.stringify(request));writeFileSync(root+'/tokens.json',JSON.stringify(transcript));database.close();console.log(JSON.stringify({name,result,consumed}));
}

writeFileSync(output+'/runtime-inputs.json',JSON.stringify(Object.keys(require.cache)));
